name: iam_ecomm
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# --------------------PACKAGES-------------------------
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  lottie: ^3.1.0

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0

  # ---------------- PACKAGE END---------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  image: ^4.8.0

flutter:
  uses-material-design: true

  # ------------------- LOCAL ASSETS --------------------

  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/images/categories/
    - assets/images/products/
    - assets/images/products_whitebg/
    - assets/images/packages/
    - assets/images/payments/
    - assets/images/users/
    # - assets/images/homescreen (example: add yung mga folder ng mga nasa assets)

  # ------------------- LOCAL FONTS ---------------------
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  

# ------------------- SPLASH CONFIG ---------------------
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/images/ecom_app_icon_xs.png
  image_dark: assets/images/ecom_app_icon_xs.png
  
  # App icon properties for better corner rounding
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  
  # Size and padding adjustments
  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/images/ecom_app_icon_xs.png
    image_dark: assets/images/ecom_app_icon_xs.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#272727"

  web: false

# ------------------- APP ICON CONFIG --------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ecom_app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/ecom_app_icon.png"
